// ACCIONES PARA PROYECTOS REDUCER

export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';   
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';


//ACCIONES PARA TAREAS REDUCER
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const GUARDAR_TAREA = 'GUARDAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const SELECCIONAR_TAREA = 'SELECCIONAR_TAREA';
export const EDITAR_TAREA = 'EDITAR_TAREA';

//ACCIONES PARA ALERTAS REDUCER
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//ACCIONES PARA LA AUTENTICACION
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CERRAR = 'LOGIN_CERRAR';

